//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.Permission.Test.PermissionServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "PermissionServiceReference.IPermissionService")]
    public interface IPermissionService
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPermissionService/GetPermission", ReplyAction = "http://tempuri.org/IPermissionService/GetPermissionResponse")]
        System.Data.DataTable GetPermission(string strUserName, string strPassword, int intSystemId);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPermissionServiceChannel : global::Nikita.Permission.Test.PermissionServiceReference.IPermissionService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PermissionServiceClient : System.ServiceModel.ClientBase<global::Nikita.Permission.Test.PermissionServiceReference.IPermissionService>, global::Nikita.Permission.Test.PermissionServiceReference.IPermissionService
    {
        public PermissionServiceClient()
        {
        }

        public PermissionServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public PermissionServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PermissionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PermissionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Data.DataTable GetPermission(string strUserName, string strPassword, int intSystemId)
        {
            return base.Channel.GetPermission(strUserName, strPassword, intSystemId);
        }
    }
}