//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace Nikita.WinForm.ExtendControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nikita.WinForm.ExtendControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveTab_Close {
            get {
                object obj = ResourceManager.GetObject("ActiveTab_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ActiveTabHover_Close {
            get {
                object obj = ResourceManager.GetObject("ActiveTabHover_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Bottom {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Fill {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dockindicator_PaneDiamond_Fill_VS2012 {
            get {
                object obj = ResourceManager.GetObject("Dockindicator_PaneDiamond_Fill_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_HotSpot {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotSpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dockindicator_PaneDiamond_Hotspot_VS2012 {
            get {
                object obj = ResourceManager.GetObject("Dockindicator_PaneDiamond_Hotspot_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_HotSpotIndex {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotSpotIndex", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_HotspotIndex_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_HotspotIndex_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Left {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Right {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PaneDiamond_Top {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PaneDiamond_Top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dockindicator_PaneDiamond_VS2012 {
            get {
                object obj = ResourceManager.GetObject("Dockindicator_PaneDiamond_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelBottom {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelBottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelBottom_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelBottom_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelBottom_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelBottom_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelFill {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelFill_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelFill_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelFill_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelFill_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelLeft {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelLeft_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelLeft_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelLeft_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelLeft_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelRight {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelRight_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelRight_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelRight_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelRight_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelTop {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelTop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelTop_Active {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelTop_Active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockIndicator_PanelTop_VS2012 {
            get {
                object obj = ResourceManager.GetObject("DockIndicator_PanelTop_VS2012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_AutoHide {
            get {
                object obj = ResourceManager.GetObject("DockPane_AutoHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Close {
            get {
                object obj = ResourceManager.GetObject("DockPane_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Dock {
            get {
                object obj = ResourceManager.GetObject("DockPane_Dock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_Option {
            get {
                object obj = ResourceManager.GetObject("DockPane_Option", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DockPane_OptionOverflow {
            get {
                object obj = ResourceManager.GetObject("DockPane_OptionOverflow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InactiveTabHover_Close {
            get {
                object obj = ResourceManager.GetObject("InactiveTabHover_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LostFocusTab_Close {
            get {
                object obj = ResourceManager.GetObject("LostFocusTab_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LostFocusTabHover_Close {
            get {
                object obj = ResourceManager.GetObject("LostFocusTabHover_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        #region MyRegion
          
        internal static System.Drawing.Bitmap btnBack {
            get {
                object obj = ResourceManager.GetObject("btnBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnDrag {
            get {
                object obj = ResourceManager.GetObject("btnDrag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnFitToScreen {
            get {
                object obj = ResourceManager.GetObject("btnFitToScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnNext {
            get {
                object obj = ResourceManager.GetObject("btnNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnOpen {
            get {
                object obj = ResourceManager.GetObject("btnOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnPreview {
            get {
                object obj = ResourceManager.GetObject("btnPreview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRotate270 {
            get {
                object obj = ResourceManager.GetObject("btnRotate270", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnRotate90 {
            get {
                object obj = ResourceManager.GetObject("btnRotate90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnSelect {
            get {
                object obj = ResourceManager.GetObject("btnSelect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnZoomIn {
            get {
                object obj = ResourceManager.GetObject("btnZoomIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap btnZoomOut {
            get {
                object obj = ResourceManager.GetObject("btnZoomOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        internal static System.Drawing.Bitmap ClearFiltering
        {
            get
            {
                object obj = ResourceManager.GetObject("ClearFiltering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        internal static System.Drawing.Bitmap ColumnFilterIndicator
        {
            get
            {
                object obj = ResourceManager.GetObject("ColumnFilterIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap SortDescending
        {
            get
            {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Filtering
        {
            get
            {
                object obj = ResourceManager.GetObject("Filtering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }


        internal static System.Drawing.Bitmap SortAscending
        {
            get
            {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        #endregion

        #region MyRegion
           /// <summary>
        ///   查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string HtmlEditControl_ExecuteSystemInfo_Information {
            get {
                return ResourceManager.GetString("HtmlEditControl_ExecuteSystemInfo_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非预期的路径 &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MyModule_Process_Unexpected_path___0___ {
            get {
                return ResourceManager.GetString("MyModule_Process_Unexpected_path___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须提供一个HtmlTemplate值 的本地化字符串。
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少“##BODY##&apos;的HTML模板属性值. 的本地化字符串。
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Center {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Justify {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Left {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Right {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_CellProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ColumnProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_ColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arial 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyArial {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyArial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Courier new 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyCourierNew {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyCourierNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Garamond 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGaramond {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGaramond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Georgia 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGeorgia {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGeorgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Times 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyTimes {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verdana 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyVerdana {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyVerdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize4 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize5 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize6 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize7 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSizeStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSizeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 &lt;address&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleAddress {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预格式 &lt;pre&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleFormatted {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 1 &lt;h1&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 2 &lt;h2&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 3 &lt;h3&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleNormal {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 段落 &lt;p&gt; 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleParagraph {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AbsBottom 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AbsMiddle 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基线 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBaseLine {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底端 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居左 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignLeft {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居右 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignRight {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本顶端 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTextTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_RowProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_RowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格属性 的本地化字符串。
        /// </summary>
        internal static string Str_UIHtml_TableProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基线 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_BaseLine {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_BaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底端 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Bottom {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Middle {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复合 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶端对齐 的本地化字符串。
        /// </summary>
        internal static string Str_VerticalAlignmentType_Top {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获得空闲端口. 的本地化字符串。
        /// </summary>
        internal static string WebServer_getFreePort_Unable_to_acquire_free_port_ {
            get {
                return ResourceManager.GetString("WebServer_getFreePort_Unable_to_acquire_free_port_", resourceCulture);
            }
        }
        #endregion


        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glyphs
        {
            get
            {
                object obj = ResourceManager.GetObject("Glyphs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static  Stream DragCursor
        {
            get
            { 
                object obj = ResourceManager.GetObject("DragCursor", resourceCulture);
                return new MemoryStream(obj as byte[]);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Stream Rightarrow
        {
            get
            {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return new MemoryStream(obj as byte[]);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Stream SyntaxModes
        {
            get
            {
                object obj = ResourceManager.GetObject("SyntaxModes", resourceCulture);
                return new MemoryStream(obj as byte[]);
            }
        }
    }
}
