//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Version_UpdateLog
    {
        public long Version_Id { get; set; }
        public string Version { get; set; }
        public bool State { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Remark { get; set; }
        public string FileNames { get; set; }
    }
}
