//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Shortcut
    {
        public int Shortcut_Id { get; set; }
        public string Shortcut_Name { get; set; }
        public string Shortcut_Key { get; set; }
        public string Shortcut_Form { get; set; }
        public string NavigaUrl { get; set; }
        public string Shortcut_ImageUrl { get; set; }
        public Nullable<int> Sort { get; set; }
        public string System { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
