//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Exception
    {
        public int Exception_Id { get; set; }
        public Nullable<int> SystemId { get; set; }
        public Nullable<int> EventId { get; set; }
        public string Category { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Severity { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string MachineName { get; set; }
        public string IPAddress { get; set; }
        public string AppDomainName { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public string ThreadName { get; set; }
        public string Win32ThreadId { get; set; }
        public string Message { get; set; }
        public string FormattedMessage { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateName { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
