//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_AccountUser
    {
        public int Module_Id { get; set; }
        public long User_Id { get; set; }
        public string Allowed_Operator { get; set; }
        public bool IsAllow { get; set; }
    }
}
