//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Role
    {
        public int Role_Id { get; set; }
        public Nullable<int> SystemId { get; set; }
        public string RoleNumber { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int AllowEdit { get; set; }
        public int AllowDelete { get; set; }
        public int IsVisible { get; set; }
        public Nullable<int> OwnerCompany { get; set; }
        public string PY { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Bloc_Id { get; set; }
        public string BlocName { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditUserName { get; set; }
        public string EditDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> State { get; set; }
    }
}
