//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_SetOrd_Tree
    {
        public int SetTree_Id { get; set; }
        public string SetTree_Name { get; set; }
        public string SetTree_EName { get; set; }
        public string SetTree_Key { get; set; }
        public byte SetTree_Level { get; set; }
        public int Parent_SetTree_Id { get; set; }
        public Nullable<int> SetTree_Type { get; set; }
        public string SetTree_PY { get; set; }
        public Nullable<int> SetTree_Sort { get; set; }
    }
}
