//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nikita.DataAccess.EF.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Organize
    {
        public int Organize_Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Category { get; set; }
        public string OuterPhone { get; set; }
        public string InnerPhone { get; set; }
        public string Fax { get; set; }
        public string Postalcode { get; set; }
        public string Address { get; set; }
        public string Web { get; set; }
        public string Bank { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> Layer { get; set; }
        public Nullable<int> IsInnerOrganize { get; set; }
        public Nullable<int> DeletionStateCode { get; set; }
        public string PY { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Bloc_Id { get; set; }
        public string BlocName { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditUserName { get; set; }
        public string EditDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> SystemId { get; set; }
    }
}
