//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewellerySimpleSystem.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_Log
    {
        public int Log_Id { get; set; }
        public Nullable<int> SystemId { get; set; }
        public string ProcessId { get; set; }
        public string ProcessName { get; set; }
        public string MethodId { get; set; }
        public string MethodName { get; set; }
        public string Parameters { get; set; }
        public string IPAddress { get; set; }
        public string UrlReferrer { get; set; }
        public string WebUrl { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateName { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
