//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewellerySimpleSystem.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bse_User
    {
        public int User_Id { get; set; }
        public string Number { get; set; }
        public string UserName { get; set; }
        public string Realname { get; set; }
        public string NiName { get; set; }
        public string UserFrom { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public string Duty { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Lang { get; set; }
        public string Sex { get; set; }
        public string Birthday { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string QQ { get; set; }
        public string SFZNumber { get; set; }
        public string HomeAddress { get; set; }
        public string HomeTel { get; set; }
        public string WorkAddress { get; set; }
        public string WorkTel { get; set; }
        public string Theme { get; set; }
        public Nullable<System.DateTime> AllowStartTime { get; set; }
        public Nullable<System.DateTime> AllowEndTime { get; set; }
        public Nullable<System.DateTime> LockStartDate { get; set; }
        public Nullable<System.DateTime> LockEndDate { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> PreviousVisit { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<int> IsStaff { get; set; }
        public Nullable<int> IsVisible { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public string Question { get; set; }
        public string AnswerQuestion { get; set; }
        public Nullable<int> UserAddressId { get; set; }
        public string AuditStatus { get; set; }
        public string PY { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string DeptName { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> Bloc_Id { get; set; }
        public string BlocName { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> EditUserId { get; set; }
        public string EditUserName { get; set; }
        public string EditDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> SystemId { get; set; }
    }
}
